# Generated by Django 3.1.7 on 2021-03-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dashboard', '0005_auto_20210310_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='retina_image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
    ]
